### ISSUE TITLE
Opening Terminal Suggestion

### ISSUE THREAD

**Issue by paulknyc** [learn-co-curriculum/first-terminal#11]
I like to open Terminal by hitting Command+Space which opens up Spotlight quickly, then typing in 'Terminal' and hitting Enter.

**Comment by AnnJohn** [comment]
@paulknyc Thanks for the suggestion! We're going to icebox the issue for now and someone from the team will look at it soon.

**Comment by SophieDeBenedetto** [comment]
leaving iceboxed for now.

**Comment by aviflombaum** [comment]
Thanks @paulknyc we mention that method and agree it's super effective! Closing for now.
